spring.application.name=api
spring.datasource.url=jdbc:postgresql://postgres:5432/lanmsgdb
spring.datasource.username=lanmsg
spring.datasource.password=lanmsg123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
